### ISSUE TITLE
Use faster script

### ISSUE THREAD

**Issue by timothyarmes** [reywood/meteor-iron-router-ga#15]
I expect that most Meteor developer expect their users to be using a modern browser. I propose that for that reason you should use the "Alternative Asynchronous Snippet" as explained here:

https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#localhost

It'll still work on old browsers, so there isn't a compatibility issue.

**Comment by reywood** [comment]
Good idea! Just pushed a new version with this change. Give it a shot and let me know if you experience any issues.
