### ISSUE TITLE
No GA tracking code being added?

### ISSUE THREAD

**Issue by davidrea** [reywood/meteor-iron-router-ga#19]
I've just deployed an app to meteor (http://indxd-testdrive.meteor.com/) and am not seeing the GA tracking code added.

I've added reywood:iron-router-ga to my project, configured the router with trackPageView:true, and added my tracking code to settings.json. I deployed with the --settings switch and am seeing the GA tracking ID in the public settings (via "view source"). I also see the GA script include.

The GA Tracking ID control panel, however, still lists my site as "Status: Tracking Not Installed"

Would appreciate any assistance you can provide!

**Comment by reywood** [comment]
Looks like it's working. Sometimes there's some lag between when you put the tracker up on your site and when the GA dashboard shows it as active. I recommend you install the [GA Debug](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) browser extension. It'll allow you to see if and when data is being sent to GA.

**Comment by davidrea** [comment]
Thanks - I installed the GA Debug extension and got a better look. Weirdly, it still says that "Tracking Not Installed" while real time pageviews are showing up in the reporting section!

**Comment by reywood** [comment]
From what I've seen, it can take up to a day for that "not installed" message to go away. If GA Debug is telling you that data is being sent and real time hits are appearing in the dashboard, then you're good. All that's required now is patience :)
