### ISSUE TITLE
On iOS / Cordova, left screen idle overnight, when turned back on GA stopped tracking pageviews.

### ISSUE THREAD

**Issue by slickdev** [reywood/meteor-iron-router-ga#20]
Using the iron-router config option on iOS, I turned the device back on and browsed pages while looking at the Real-time monitor on GA. I noticed that pages were not being tracked. After quitting the app and re-opening, it began tracking again.

Any idea what might be causing this?

**Comment by reywood** [comment]
I'll see if I can reproduce it.
