### ISSUE TITLE
Rewrite as IronRouter plugin

### ISSUE THREAD

**Issue by tgoorden** [reywood/meteor-iron-router-ga#21]
It seems that the code currently overwrites Router.route, whereas it would seem a lot simpler/predictable to just provide an IronRouter plugin.

**Comment by reywood** [comment]
Thanks. I'll look into this.

**Comment by GabrielGil** [comment]
+1 :)

**Comment by Taik** [comment]
+1 would be great!

**Comment by reywood** [comment]
done

**Comment by GabrielGil** [comment]
And it only took two years! :D

**Comment by reywood** [comment]
slow and steady
