### ISSUE TITLE
Analytics Not reporting. 

### ISSUE THREAD

**Issue by tonyarash** [reywood/meteor-iron-router-ga#22]
I recently used this package with iron-router on Meteor 1.03. I launched the app with meteor deploy using the setting.josn. The Google analytics script tag does show up in the head but the tracking snippet is not found and GA is not reporting. Here is the site http://tabletlisting.com/.

**Comment by jhmacdon** [comment]
I'm having the same issue

**Comment by reywood** [comment]
Please try installing and activating the [GA Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en). It will show you whether or not data is being sent to GA. If you have just created a new tracking ID, it may take a day or more for data to show up in the GA dashboard.

**Comment by Atu** [comment]
@reywood I have the same issue, and I have this error message 
`````
Executing Google Analytics commands.
Running command: ga("set", "page", "/")
Command ignored. Unknown target: undefined

**Comment by reywood** [comment]
Do you have the correct [settings configured](https://github.com/reywood/meteor-iron-router-ga#meteor-settings)?

**Comment by Atu** [comment]
Yes for sure.

`````
{
  "public": {
    "ga": {
      "id": "UA-56575619-5"
    }
  }
}

**Comment by jhmacdon** [comment]
Yeah, it seems I was just being impatient. I thought that realtime should work instantly, but that was wrong.

**Comment by reywood** [comment]
@Atu Sorry, I'm unable to recreate your issue. You don't have any other GA related code on your site, do you? The best I can recommend is Googling "Command ignored. Unknown target: undefined" and seeing if anything sounds similar to your setup.

**Comment by jhmacdon** [comment]
@Atu This might help with your issue:
https://groups.google.com/forum/#!topic/google-analytics-analyticsjs/mayu2cf1d0k

**Comment by williamli** [comment]
I am seeing the same error on my project.
I used https://atmospherejs.com/ogourment/settings to load the Meteor.settings the first thing when the app startup..

The only way to fix it is to manually call ga('create', 'UA-61.... at client during startup as well.

**Comment by Atu** [comment]
@reywood I found my issue, when you are dealing with modulus.io. You need to do `$ modulus env set METEOR_SETTINGS "$(cat settings.json)"`

**Comment by williamli** [comment]
yep. seems https://atmospherejs.com/ogourment/settings <- doesn't load in the settings correctly / at the correct time (i was using that) and was having problem. if METEOR_SETTINGS were loaded in env, then it's fine

**Comment by reywood** [comment]
Ah, yes. Any time you are deploying your app to any server (not just modulus.io), you need to use the `METEOR_SETTINGS` environment variable. More info in the [meteor docs](http://docs.meteor.com/#/full/meteor_settings).
