### ISSUE TITLE
Meteor.settings alternate implementation, easier set up please

### ISSUE THREAD

**Issue by keyscores** [reywood/meteor-iron-router-ga#23]
Thanks for providing this package.
As a newbie to meteor I found it very frustrating to find documentation for Meteor.settings.
IMHO the set up would be much cleaner if the "tracker id" was just defined in Router.configure . Or atleast provide both options with Meteor.settings be an advanced option.

Am I missing something? Is there a reason the tracker code must be set in a settings.json ? 

PS. To anyone else lost and reading this, run: 
 >meteor --settings settings.json 
or
 >meteor deploy domain.com --settings settings.json
... yes every time you deploy or run)

**Comment by reywood** [comment]
Is your complaint that Meteor's documentation of the settings feature is not clear? If so, you'll have to take that up with the Meteor folks. The README for this project links directly to the relevant section of the docs. Perhaps the link is not prominent enough?

As for why iron-router-ga is configured via settings, many people do not want to muddy their production analytics with page views, events, etc generated while they are doing development work or testing their app in a staging environment. Configuring via settings allows them to easily use different tracking IDs for each environment. Granted, this is only easy once you're familiar with how Meteor settings work.

**Comment by keyscores** [comment]
I'm very happy with this package, thanks again for your dedication to the
community.

Ok, I get that users need to control settings in environments. The
suggestion is that this variable is disabled in debug mode.

Yes the meteor docs could be clearer. It would be helpful if you reminded
users in the readme how to deploy Meteor.settings.

You can close this ticket now. Thanks!
