### ISSUE TITLE
debugging approach?

### ISSUE THREAD

**Issue by dcsan** [reywood/meteor-iron-router-ga#24]
I've installed the plugin and setup a UA account but don't get any events sent to GA from iron:router page views.
just wondering what other steps i can take to debug?

settings are reading OK
![image](https://cloud.githubusercontent.com/assets/514002/6999392/205a9b14-dbbe-11e4-93ed-2c47f8af74c7.png)

![image](https://cloud.githubusercontent.com/assets/514002/6999394/351e95fa-dbbe-11e4-9cf8-920d6eaee345.png)

![image](https://cloud.githubusercontent.com/assets/514002/6999385/f0d87c76-dbbd-11e4-905d-62a01c46934c.png)

when I tried [google's own analytics debugger ](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) it picks up my GA ID fine

I'm using the GA realtime dashboard to track things.

in the router I also have my own onRun block - but removing that doesn't change anything.

```
Meteor.startup ->
  if Meteor.isClient
    Router.configure
      trackPageView: true
      layoutTemplate: "ionicLayout"
      onRun: -> Trix.page()

```

triggering events manually from the console works and additionally I see a user in the GA dashboard then.

![image](https://cloud.githubusercontent.com/assets/514002/6999413/f2369584-dbbe-11e4-9118-2a0c68be86e6.png)

**Comment by dcsan** [comment]
additinoally I'm not able to verify the site using the GA method

Verification failed for http://comicenglish.com/ using the Google Analytics method (less than a minute ago). The Google Analytics tracking code on your site looks malformed. Learn more.

**Comment by reywood** [comment]
If you just created the tracker in the GA dashboard, you'll have to wait a day or two before data starts to show up.

**Comment by dcsan** [comment]
thanks. i switched to an okgrow plugin and that worked immediately so i think it's something with this package, but don't have any further info.

**Comment by dcsan** [comment]
btw you don't trust the GA realtime dashboard? it seems fairly accurate?

**Comment by reywood** [comment]
I haven't had any issues with real-time reporting. The delay in analytics reporting after creating a new tracker is well known. The note at the end of [this help article](https://support.google.com/sites/answer/97459?hl=en) states that it can take up to 24 hours for data from a new tracker to show up.
