### ISSUE TITLE
Experiments: Not all users being tracked.

### ISSUE THREAD

**Issue by keyscores** [reywood/meteor-iron-router-ga#25]
I've set the experiment quota to 100% of users. However I'm only seeing 1/10th of my visitors in the "experiment sessions" results.

Manually accessing the website on different browsers yields the A/B variation. So I can see it working.

However the experiments code validation says it is not finding the code on the site.

**Comment by reywood** [comment]
Hmm, I don't have any satisfying answers for you. Is it possible that not all of the users visiting your site are landing on the page you're experimenting on?

**Comment by reywood** [comment]
I'm curious if you see similar numbers under Behavior > Events with category "iron-router-ga" and action "Choose experiment variation" to those for "experiment sessions".

Going to close this for now since I haven't heard back, but feel free to comment/re-open if you're still having issues.

**Comment by keyscores** [comment]
So I let the experiment run longer. Now the two numbers seem closer. However they are inverted. 
I have 1,660 sessions for the route tested
and 1,885 experiment sessions

Initially I thought it was excluding returning users. Now I am not sure why the numbers would be different.

**Comment by maxko87** [comment]
I am having the same issue. I'm running an experiment with 100% of users. The way I can tell that something is wrong is that the total number of Goal Completions (the target of my experiment) don't add up. For example, on March 5, there was one Goal Completion on each of the Original and the Experiment variants (2 total conversions reported):

https://www.dropbox.com/s/c99dk7wq0ogpp2h/Screenshot%202017-03-06%2012.29.02.png?dl=0

But there were 8 total number of Goal Completions on that day:

https://www.dropbox.com/s/k2783tbrp24vd7u/Screenshot%202017-03-06%2012.30.09.png?dl=0
