### ISSUE TITLE
Page meta titles

### ISSUE THREAD

**Issue by for2ne** [reywood/meteor-iron-router-ga#26]
Hi!
How do I properly consider the page meta titles?
http://take.ms/N1Xwu

**Comment by reywood** [comment]
How are you changing the page title in Meteor?

**Comment by for2ne** [comment]
with https://github.com/DerMambo/ms-seo/

for all pages:

`````
Meteor.startup(function() {
  if (Meteor.isClient){
    var title = 'page title';
    var description = 'page description';

    return SEO.config({
      title: title,
      meta: {
        'description': description
      },
       og: {
         'type' : 'website',
         'title': title,
         'description': description
       }
    });
  }
});
`````

**Comment by todda00** [comment]
What I am experiencing with page titles is the reported page title is always from the previous page. I have tried to use the following 3 packages with the same result: 
https://atmospherejs.com/manuelschoebel/ms-seo
https://atmospherejs.com/yasinuslu/blaze-meta
https://atmospherejs.com/lookback/seo

I am currently using the global setup like this: 

```
Router.configure({
    trackPageView: true
});
```

**Comment by forumd** [comment]
any solution?

**Comment by kvnadesara** [comment]
+1

**Comment by javascriptlove** [comment]
I know this thread is old, but the problem persists, here's why.. Let's say a route has 

```
    action: function() {
        if (this.ready()) {
            var item = SomeCollection.findOne({ _id: this.params.id });
            SEO.set({
                title: item.title,
                meta: {
                    'description': item.description
                }
            });
            this.render();
        }
    },
```

It takes some time to load the item, hence the title/description is only available after `this.ready()`, but `onRun` was already ran after first time it ran `action()` with ready() returning false yet and subscriptions being not ready

**Comment by reywood** [comment]
I believe this could be solved with a simple router plugin like this:

```javascript
Iron.Router.plugins.seo = function seo(router) {
    router.onRun(setSeo);
    router.onBeforeAction(setSeo);
};

function setSeo() {
    var seo = this.lookupOption('seo');
    if (seo) {
        SEO.set(seo);
    }
    this.next();
}
```

Then you can configure your router like so:

```javascript
if (Meteor.isClient) {
    Router.configure({
        seo: {
            title: 'Default Site Title',
            meta: {
                description: 'Default site description'
            }
        },
        trackPageView: true
    });

    Router.plugin('seo');
}

Router.route('/', {
    name: 'home',
    seo: {
        title: 'Home Page Title',
        meta: {
            description: 'Home page description'
        }
    }
});
```

Using a plugin should ensure that the SEO properties are always set before the page view is tracked. Let me know if this doesn't solve the problem.
