### ISSUE TITLE
Build fails on CircleCi

### ISSUE THREAD

**Issue by skwasha** [reywood/meteor-iron-router-ga#27]
I can't explain why... But adding this package to my project will cause a build of a docker image on CircleCi to fail. I've been happily sending my commits to CircleCi, which then grabs the latest and using the meteorhacks/meteord image, goes and builds a docker image of my app for testing and later deployment. However, when I add this package I get an error like the following:

```
/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: EINVAL, chown '/tmp/.tmpywvy0q/reywood_iron-router-ga-0.6.0'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:395:16)
...
```

There's a good ~25 or so other packages I can add or remove with no consequence. It's only this one and the numerals:numerals packages that cause this problem (either of them will give similar errors).

So, any idea what's happening to cause this? For what it's worth it also appears isolated to CircleCi's build env (which utilizes lxc). Unfortunately, I don't know enough about what's truly happening under the covers to be able to provide more info.

**Comment by reywood** [comment]
Hmm, I've successfully built Docker images with Meteor apps that use this package, so I'm not sure what the problem is. If you figure it out, please let me know.

**Comment by skwasha** [comment]
I've no idea frankly. As I noted, it's specific to CircleCi's environment. I know they're using LXC, so I'm sure there's something going on there. But exactly what? Who knows?

**Comment by benwiley** [comment]
I'm having this same issue with velocityjs:velocityjs.  I submitted a Circle CI help request but they weren't sure what to do.

**Comment by benwiley** [comment]
@reywood do you mind sharing what your parent Docker image was?  Maybe changing the foundation of the container would help?

**Comment by reywood** [comment]
In the past, I've used node:0.10.38 as the base image.

**Comment by Levino** [comment]
Anyone able to fix this? Really annoying.

**Comment by reywood** [comment]
Looks like a bug with Meteor (meteor/meteor#4566). No idea why it only affects certain packages.

**Comment by alexisvincent** [comment]
Did anyone manage to fix this?

**Comment by Levino** [comment]
I use a workaround that works well. This here: https://github.com/meteor/meteor/issues/4566#issuecomment-160780199
