### ISSUE TITLE
On cordova App.accessRule('*.google-analytics.com/*') is needed

### ISSUE THREAD

**Issue by teknologist** [reywood/meteor-iron-router-ga#29]
I guess maybe you should add in the readme that for Meteor Cordova builds you need to add this:

`App.accessRule('*.google-analytics.com/*');`

to your mobile-config.json

**Comment by reywood** [comment]
Done

**Comment by zaidiqbalvf** [comment]
@reywood GA plugin is working great with the website but not helping me in cordova. From mobile apps it is not giving me readings for GA
