### ISSUE TITLE
Problem in cooperation with iron-routers "ensureSignedIn" Plugin

### ISSUE THREAD

**Issue by Jehu** [reywood/meteor-iron-router-ga#32]
Seems not to work with the iron-router plugin 'ensureSignedIn'.

My rule:

```
Router.plugin('ensureSignedIn', {
  except: ['frontpage','logout', 'termsOfUse', 'atSignIn', 'atSignUp', 'atForgotPwd', 'atResetPwd']
});
```

As soon as i add "reywood:iron-router-ga", all pages requires login.

**Comment by reywood** [comment]
Will take a look.

**Comment by reywood** [comment]
iron-router-ga is now a plugin which I think might fix this. Closing for now, but let me know if the problem persists and I'll reopen.
