### ISSUE TITLE
This package breaks orionjs

### ISSUE THREAD

**Issue by ffxsam** [reywood/meteor-iron-router-ga#34]
When adding this package, the admin interface in Orion (for collections) fails.

> pathFor couldn't find a route named "collections.products.index"

**Comment by reywood** [comment]
Will take a look. Probably more proof that I need to turn this package into a plugin.

**Comment by ffxsam** [comment]
I believe this is the line in question in the orionjs package:

https://github.com/orionjs/orion/blob/88b800a39e1f4925559d567b9f248adbf3159122/packages/bootstrap/views/sidebar/sidebar.html#L40

The `routeName` is coming up empty which it shouldn't. And this only occurs when your GA package is installed. But it's hard to say whether the issue is with the GA package or with Orion.

**Comment by jannikkeye** [comment]
I can confirm that the orion admin interface works even when this package is installed!

**Comment by reywood** [comment]
Might be fixed now that iron-router-ga is a router plugin. Closing for now, but will reopen if the problem still exists.
