### ISSUE TITLE
Problem with uncorrect Router.route override

### ISSUE THREAD

**Issue by martinopic** [reywood/meteor-iron-router-ga#38]
While investigating a bug reported for Iron Router i18n (https://github.com/yoolab/iron-router-i18n/issues/66) I found out that the bad behavior is caused by a wrong override of Iron Router ```Router.route``` method made by metor-iron-router-ga.

The "signature" of this method is ```Router.prototype.route = function (path, fn, opts)``` because it can be called with options as a second argument or with a function as the second argument and options on the third, meteor-iron-router-ga is just support the first type of call overriding the method as: ```Router.route = function route(name, options)```.

This is causing Iron Router i18n problems as it uses the complete "signature" for override but it could also cause problems to other people using the second type of call (path, function, options).

**Comment by reywood** [comment]
Thanks for reporting. Fixed in 0.6.1.
