### ISSUE TITLE
Using Meteor.userId() as the user identifier

### ISSUE THREAD

**Issue by jstoeffler** [reywood/meteor-iron-router-ga#40]
So Google Analytics [allows to track users with a custom app-defined user id](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-id). Using this feature, we could track users cross-devices.
Plus, unless I missed anything, it doesn't sound complicated:

		function initTracker() {
		    var createOptions = gaSettings.create || 'auto';

		    if(createOptions.useMeteorUserId) {
		    	delete createOptions.useMeteorUserId;
		    	if(Meteor.userId()) {
		    		createOptions.userId = Meteor.userId();
		    	}	
		    }
		    
		   	window.ga('create', gaSettings.id, createOptions);
		}

**Comment by reywood** [comment]
Added new `trackUserId` option to support this.

**Comment by jstoeffler** [comment]
Great, thanks!

Just wondering, it looks like the ga('set', '&uid' method is called even when the user isn't connected, right? I'm not sure how GA handles this, but it feels safer to call it only when we have a value, like:

    if (gaSettings.trackUserId) {
        Tracker.autorun(function() {
            if (Meteor.loggingIn() || !Meteor.userId()) { return; }
            window.ga('set', '&uid', Meteor.userId());
        });
    }

**Comment by reywood** [comment]
If the user logs out, the existing code will set the userId to null. The modification you suggest would leave the userId set to the previously logged in user.

**Comment by jstoeffler** [comment]
Quite true. So we're sure a that if the userId is set to null, that will make GA use it's own identification system (and not considering all anonymous users as the same user) ?

**Comment by reywood** [comment]
The GA Debug browser extension indicates that no userId field is sent when `&uid` is set to null.

**Comment by jstoeffler** [comment]
Ok, perfect then! Thanks for the quick implementation :)
