### ISSUE TITLE
Set configuration with .config({ ... })

### ISSUE THREAD

**Issue by servel333** [reywood/meteor-iron-router-ga#41]
As a developer, I would like to have the option of using system environment variables to load configuration.

I'm not looking to remove `iron-router-ga`'s use of `Meteor.settings`, but instead looking to add an alternative use of something like `IronRouterGa.configure({ ... })` or `Router.configure({ ... })`.

The reason for this is because it seems like there is no way that I can find to set the `Meteor.settings` from within the codebase and have it get to the client before this package loads.

It also seems pretty common (perhaps a de facto standard) for packages that need configuration to load it using a `.config({ ... })` method.

**Comment by reywood** [comment]
Hmm, iron-router-ga is a client side package, so I'm having trouble envisioning how we'd get environment variables into its configuration on the client without doing something like `Meteor.call('getIronRouterGAConfig', ...)` on the client before setting up the tracker. That seems like it would add an undesirable delay though. How do you see this working?

**Comment by servel333** [comment]
I guess that's exactly the problem I'm having. I wouldn't want a delay for developers who are using the settings, but I also would like a way to fill out the configuration from the server side.

Perhaps this package can expose a method that fetches the configuration from the server but only calls it if the settings are missing. Something like this:

```js
// server-side

var _globalConfig = {};

IronRouterGa = {
  config: function(config){
    if (config) {
      _globalConfig = config;
    }

    return _globalConfig;
  }
};

Meteor.method({
  get_iron_router_ga_config: function(){
    return IronRouterGa.config();
  }
});

// client-side

var load_ga = function(config){ ... };

if (! Meteor.settings.public.ga) {
  load_ga(Meteor.settings.public.ga);
}
else {
  Meteor.call('get_iron_router_ga_config', function(err, config){
    load_ga(config);
  });
}

// developer using package server-side
IronRouterGa.config({
  // Same structure as Meteor.settings.public.ga
  id: process.env.GA_TRACKING_ID
});
```

`IronRouterGa` is just an example. You could also pull the config out of the iron-router config.

**Comment by reywood** [comment]
I just ran a little test, and this is actually much easier to accomplish by simply overwriting the setting on the server side when meteor first starts. Create a file that only runs on the server side with the following contents.

```javascript
if (process.env.GA_TRACKING_ID) {
    Meteor.settings.public.ga.id = process.env.GA_TRACKING_ID;
}
```

If the environment var is set, the Meteor setting will be overwritten and the new setting will be available on the client. I believe this will satisfy your need.

**Comment by servel333** [comment]
I experimented with doing basically that and it didn't work. Maybe there's something else going on in my project because `Meteor.settings` is `undefined`. I'll take a closer look at it.

**Comment by reywood** [comment]
Initialization of the Meteor.settings object may vary from one version of Meteor to the next. My test used 1.2. If you're using an earlier version and if you're not using a settings file when you start meteor, you may have to initialize the `public` part yourself. Try something like:

```javascript
Meteor.settings = Meteor.settings || {};
Meteor.settings.public = Meteor.settings.public || {};
Meteor.settings.public.ga = Meteor.settings.public.ga || {};
```

**Comment by servel333** [comment]
I tried that exact code actually, as well as the below code.

I experimented with Lodash to confirm this does what I think it does, where things in `Meteor.settings` overrides things in the third parameter.

```
Meteor.settings = lodash.defaultsDeep({}, Meteor.settings, {
  public: {
    ga: {
      id: process.env.GA_TRACKING_ID
    }
  }
});
```

After this code, the server side `Meteor.settings` has what I expect, but `public` doesn't make it to the client. I'm not sure what's going on.

I just ran this code in my application:

```
"use strict";

console.log('Meteor.settings:', Meteor.settings);

if (Meteor.isServer) {
  Meteor.settings = Meteor.settings || {};
  Meteor.settings.public = Meteor.settings.public || {};
  Meteor.settings.public.ga = Meteor.settings.public.ga || {};
  Meteor.settings.public.ga.id = 'test';
}

console.log('Meteor.settings:', Meteor.settings);
```

And in the browser console, I can see the settings is undefined on the client. It must be the version of Meteor I'm running. I'll bet the public settings get sent to the client before any of my code is executed.

**Comment by servel333** [comment]
Another idea that might be worth thinking about: what if you released a separate package with the delayed loader using a `Meteor.methods`. That way, depending on what the need is, people can just choose a different package to get the different behavior. It's just a thought.

**Comment by reywood** [comment]
I'm curious what version of Meteor you're running.

**Comment by servel333** [comment]
```
meteor --version
Meteor 1.1.0.3
```

**Comment by reywood** [comment]
For what it's worth, I put together a project that shows this working if various ways.

https://github.com/reywood/cuddly-octo-kumquat
