### ISSUE TITLE
ga var is not available in server-side code... possibly update readme to reflect this.

### ISSUE THREAD

**Issue by evolross** [reywood/meteor-iron-router-ga#42]
Great package.  I think you might want to clarify something though in your readme.

It says `you will have access to the ga function anywhere in your Meteor code`, but I'm finding that `ga` is only recognized in "client" code.

As someone just discovering the package I assumed this meant your package adds the `ga` global variable to the entire Meteor application so that it can be called from "server" code too, but I'm finding `ga` isn't defined in "server" code.  Try accessing it in the Meteor Shell for example.  It would be awesome if this were the case, then we could add GA events for anything happening on the server side too - which sometimes can be something initiated by the client, but isn't necessarily associated with a button click or UI transaction (e.g. some delayed or repeated action).

So it looks like you've added the standard Google Analytics browser var `ga` and it's accessible on the client-side only.  This is still awesome, but you may want to update your readme as this confused me for a while.  With that said, I'm also an analytics newb.

Thanks!

**Comment by reywood** [comment]
Good point. README updated.
