### ISSUE TITLE
Its not tracking all routes

### ISSUE THREAD

**Issue by sourabh-shankar** [reywood/meteor-iron-router-ga#43]
We used this package in a mobile app that we build using meteor and cordova. Now, its only tracking routes that are defined in "routes.js" globally. Most the routes in our app are defined in separate individual modules. Ex: "browse" module has a route file "r_browseroutes.js" defined in "\client\views\modules\browse\helpers" directory. A sample route defined in this file is:
```javascript
Router.route('/browse-categoryselection',function(){
    this.render('browse_categoryselection',{
        name : 'browse.categories',
        data : {
        }
    });
});
```
The GA is not tracking these routes. Not sure whether its GA issue or package issue.

**Comment by reywood** [comment]
Are you using the following to enable page view tracking?

```javascript
Router.configure({
    trackPageView: true
});
```

If so, where do you have that snippet?

**Comment by sourabh-shankar** [comment]
I have specified following settings:
1. \settings.json
```javascript
"public": {
        "ga": {
            "id": "UA-xxxxxxxx-1"
        }
    },
```
2. \client\helpers\routes.js
```javascript
Router.configure({
    layoutTemplate: 'common',
    trackPageView: true
});
```

**Comment by reywood** [comment]
Meteor executes the most deeply nested files first, so code in `\client\views\modules\browse\helpers` will run before code in `\client\helpers\routes.js`. This means that the `trackPageView: true` option is not set when the `/browse-categoryselection` route is configured. You will either need to move `\client\helpers\routes.js` to a deeper folder or specify the `trackPageView` option directly on your route, like so:

```javascript
Router.route('/browse-categoryselection',{
    trackPageView: true,
    action: function(){
        this.render('browse_categoryselection',{
            name : 'browse.categories',
            data : {
            }
        });
    };
});
```

**Comment by sourabh-shankar** [comment]
How about following route:
```javascript
Router.route('/browse-categoryselection',function(){
    trackPageView: true;
    this.render('browse_categoryselection',{
        name : 'browse.categories',
        data : {
        }
    });
});
````
Will it work?

**Comment by reywood** [comment]
That's not valid JavaScript.
