### ISSUE TITLE
How to programatically override GA site ID?

### ISSUE THREAD

**Issue by j20** [reywood/meteor-iron-router-ga#44]
Thanks for creating this package!

Is it possible to programmatically override the GA ID that is set in the config? If so, in which file should that be placed?

The use case is that I need to specify multiple different GA tracking IDs, stored in different properties in my config file, and need to use JavaScript to switch up which one is used so that only the correct one is used. 

I've tried creating a file at client/lib/ga.js with the following code `ga('create', mySiteIdVar, 'auto');` but it did not override the GA ID set for this package within the config.

**Comment by reywood** [comment]
You can add another tracker using the following snippet in your client side code.

```javascript
ga('create', 'UA-XXXX-Y', {'name': 'secondTracker'});
```

Then you can do the following to, for instance, send an event.

```javascript
ga('secondTracker.send', 'event', category, action, label, value);
```
