### ISSUE TITLE
How to use multiple tracking codes in multiple pages?

### ISSUE THREAD

**Issue by anaxyd** [reywood/meteor-iron-router-ga#46]
Hello!

Is it possible to track multiple pages with multiple tracking codes?

E.g.:

Subpage 1 : Seller of Cars
Visitors on these pages should be tracked with trackingcode 1

Subpage 2 : Seller of Gifts
Visitors on these pages should be tracked with trackingcode 2

Is this possible?

**Comment by anaxyd** [comment]
Nobody knows?

**Comment by reywood** [comment]
Check out my answer to #44
