### ISSUE TITLE
Not finding GA ID from settings

### ISSUE THREAD

**Issue by badmark** [reywood/meteor-iron-router-ga#47]
Despite having the settings in settings.json I continue to receive this error:

iron-router-ga: settings not found

**Comment by reywood** [comment]
You are running meteor using `meteor --settings settings.json`? If so, I would need to see your settings file to comment further.

**Comment by badmark** [comment]
settings was not being read the same since the update(1.3) (in production), have to manually pass the JSON string into METEOR_SETTINGS for it to be read.

This is not an issue with meteor-iron-router-ga, it was entirely on my end.

**Comment by reywood** [comment]
Ah, was not aware of that. Good to know.
