### ISSUE TITLE
Enable warning message if "ga" is not found

### ISSUE THREAD

**Issue by advancedsoftwarecanada** [reywood/meteor-iron-router-ga#49]
Great plugin, but as a new Meteor user, it would be fantastic to know if my settings have been properly loaded.

I did not properly place the GA id in the "public" section of my Json config. Was a bit of a pain to diagnose. Would have been great to see an error:

"Iron Router GA was not found, please check to make sure you have defined it in the public part of your settings.json".

Great plugin otherwise, running on www.SkyRooms.io 🗡

**Comment by reywood** [comment]
You should see a warning logged to the browser's JavaScript console. It reads `iron-router-ga: settings not found`.
